services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dolibarr
    volumes:
      - db_vol:/var/lib/mysql

  # postgres:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_PASSWORD: root
  #   volumes:
  #     - db_vol:/var/lib/postgresql/data

  web:
    image: dolibarr/dolibarr:latest
    environment:
      # DOLI_DB_TYPE: pgsql
      # DOLI_DB_HOST: postgres
      # DOLI_DB_HOST_PORT: 5432
      DOLI_DB_TYPE: mysqli
      DOLI_DB_HOST: mariadb
      DOLI_DB_HOST_PORT: 3306
      DOLI_DB_USER: root
      DOLI_DB_PASSWORD: root
      DOLI_DB_NAME: dolibarr
      DOLI_URL_ROOT: "http://0.0.0.0"
      DOLI_ADMIN_LOGIN: "admin"
      DOLI_ADMIN_PASSWORD: "admin"
      PHP_INI_DATE_TIMEZONE: "America/New_York"
      DOLI_PROD: 0
    ports:
      - "8080:80"
    volumes:
      - data:/var/www/documents
      # - /mnt/e/arrowhead/dolibarr_custom:/var/www/html/custom
      - /mnt/e/dolibarr/htdocs/:/var/www/html

volumes:
  db_vol:
  data:
